In [165]:
# Author: Davide Aloi - PhD student - University of Birmingham
# Electrode coordinates inter-individual variability.

import numpy as np
import os
import glob

## Parameters and variables: 
coords_folder = 'C:\\Users\\davide\\Documents\\GitHub\\wp1_2_roast\\electrode_coords\\'

# List of electrodes coordiantes (already in the MNI space)
wp1a_elect_anod = np.load(os.path.join(coords_folder, 'wp1a_anod_mni_coords.npy'), allow_pickle = True)
wp1a_elect_anod = np.asarray(list(dict(enumerate(wp1a_elect_anod.flatten(), 1))[1].values()))

wp2a_elect_anod = np.load(os.path.join(coords_folder, 'wp2a_anod_mni_coords.npy'), allow_pickle = True)
wp2a_elect_anod = np.asarray(list(dict(enumerate(wp2a_elect_anod.flatten(), 1))[1].values()))

wp1b_elect_cath = np.load(os.path.join(coords_folder, 'wp1b_cath_mni_coords.npy'), allow_pickle = True)
wp1b_elect_cath = np.asarray(list(dict(enumerate(wp1b_elect_cath.flatten(), 1))[1].values()))

In [213]:
wp1a_mean_point = [np.mean(wp1a_elect_anod[:,0,0]), np.mean(wp1a_elect_anod[:,0,1]),
                   np.mean(wp1a_elect_anod[:,0,2])] # x y z mean for wp1a anod
wp1a_std_point = [np.std(wp1a_elect_anod[:,0,0]), np.std(wp1a_elect_anod[:,0,1]),
                   np.std(wp1a_elect_anod[:,0,2])]

wp1a_std_magnitude = np.sqrt(wp1a_std_point[0]**2 + wp1a_std_point[1]**2 + wp1a_std_point[2]**2)

print('average elect position')
print(wp1a_mean_point)
print('average distance from mean point (in mm)')
print(wp1a_std_magnitude)

dists = []
for point in wp1a_elect_anod:
    print(point)
    dist = np.linalg.norm(wp1a_mean_point-point)
    dists.append(dist)
print(np.mean(dists))
print(np.std(dists))

average elect position
[-47.67993957887996, -20.348977614532817, 70.32529149543156]
average distance from mean point (in mm)
23.015224847051435
[[-52.77677536 -11.39742422  53.2952916 ]]
[[-38.6488899   -7.          68.01664948]]
[[-40. -24.  76.]]
[[-36.90064853 -12.98541123  72.93542325]]
[[-39.25526822  -1.75040555  70.90759397]]
[[-57.  11.  53.]]
[[-47.80292797 -21.          64.89895058]]
[[-43. -10.  72.]]
[[-64.82131112 -61.02621448  62.        ]]
[[-47.60184956 -71.78307688  87.89461935]]
[[-37.3941834  -23.01784956  86.69587862]]
[[-46. -25.  73.]]
[[-39.75004339 -26.66285014  79.11219257]]
[[-51.13147873 -25.27029443  79.54389733]]
[[-39.45188731 -31.86171073  84.        ]]
[[-42. -24.  76.]]
[[-30.00915331 -18.          80.6005581 ]]
[[-56.42636693  -8.83922851  72.17897862]]
[[-64.59220171  -2.          45.26430321]]
[[-52. -18.  69.]]
[[-57.         -18.52905571  66.8682754 ]]
[[-65.39568532 -16.55398607  53.94380081]]
19.162455611059638
12.747582896945714


In [168]:
wp1b_mean_point = [np.mean(wp1b_elect_cath[:,0,0]), np.mean(wp1b_elect_cath[:,0,1]),
                   np.mean(wp1b_elect_cath[:,0,2])] # x y z mean for wp1a anod
wp1b_std_point = [np.std(wp1b_elect_cath[:,0,0]), np.std(wp1b_elect_cath[:,0,1]),
                   np.std(wp1b_elect_cath[:,0,2])]

wp1b_std_magnitude = np.sqrt(wp1b_std_point[0]**2 + wp1b_std_point[1]**2 + wp1b_std_point[2]**2)

print('average elect position')
print(wp1b_mean_point)

print('average distance from mean point (in mm)')
print(wp1b_std_magnitude)


# this should give very similar results, but we get the std of the distance as well
dists = []
for point in wp1b_elect_cath:
    dist = np.linalg.norm(wp1b_mean_point-point)
    dists.append(dist)
print(np.mean(dists))
print(np.std(dists))

average elect position
[40.92291050865536, -91.4834630773181, -19.570283168838138]
average distance from mean point (in mm)
21.615473698122862
19.386361777338966
9.560213398892941


In [214]:
wp2a_mean_point = [np.mean(wp2a_elect_anod[:,0,0]), np.mean(wp2a_elect_anod[:,0,1]),
                   np.mean(wp2a_elect_anod[:,0,2])] # x y z mean for wp1a anod
wp2a_std_point = [np.std(wp2a_elect_anod[:,0,0]), np.std(wp2a_elect_anod[:,0,1]),
                   np.std(wp2a_elect_anod[:,0,2])]

wp2a_std_magnitude = np.sqrt(wp2a_std_point[0]**2 + wp2a_std_point[1]**2 + wp2a_std_point[2]**2)

print('average elect position')
print(wp2a_mean_point)
print('average distance from mean point (in mm)')
print(wp2a_std_magnitude)

dists = []
for point in wp2a_elect_anod:
    print(point)
    dist = np.linalg.norm(wp2a_mean_point-point)
    dists.append(dist)
print(np.mean(dists))
print(np.std(dists))


average elect position
[-57.58827231722799, -19.233482379127633, 48.25523163784634]
average distance from mean point (in mm)
19.67566752836689
[[-23.33479691  -4.39206332  85.14565587]]
[[-55.19728017 -17.45362818  48.34743947]]
[[-57.61112809  -1.36258495  55.08787531]]
[[-59.89053166   0.90105325  23.12277919]]
[[-64.70750171 -34.87680537  42.00128162]]
[[-57.85577673 -22.28529809  60.69052482]]
[[-49.62648427 -35.1035952   54.28734452]]
[[-65.53141546 -12.29458189  47.56572902]]
[[-61.31870103 -35.32253712  34.4460144 ]]
[[-54.53256685 -24.21464092  20.78375697]]
[[-59.28992856 -28.10112625  52.33129257]]
[[-54.18447655 -18.10795116  53.13748956]]
[[-56.73686057 -28.43708712  50.40132207]]
[[-58.07908159 -28.82563746  42.79472083]]
[[-51.68650913 -28.19658184  53.09398472]]
[[-65.80842    -16.51363158  51.18706048]]
[[-63.65890157  -9.75675559  61.5154649 ]]
[[-70.94663572 -24.17250282  44.85577917]]
[[-60.31764567 -20.69432318  53.41151154]]
[[-52.99326444 -11.58299899  60.21147001

In [208]:
# Comparison between wp1a and wp2a in terms of electrode distance from M1 centroid
from nilearn import image
main_folder = 'C:\\Users\\davide\\Documents\\GitHub\\wp1_2_roast\\' # Project folder

## Loading AAL3 atlas and extracting M1 / Thalamus ROIs (regions of interest)
# AAL3 atlas paper: https://www.oxcns.org/papers/607%20Rolls%20Huang%20Lin%20Feng%20Joliot%202020%20AAL3.pdf 
AAl3_path = os.path.join(main_folder, 'rois', 'AAL3v1_1mm.nii')
AAL3_atlas = image.load_img(AAl3_path)

## Creating M1, Th and cerebellar masks from the AAL3 atlas. Load MNI template.
# AAL3 index for left M1 = 1
m1 = image.math_img("np.where(img == 1, 1, 0)", img = AAL3_atlas) 
m1_narray = m1.get_fdata()

def matrix_to_mni(matrix_coord, T):
    # From matrix space to MNI space
        second_arg = np.array([matrix_coord[0],matrix_coord[1],matrix_coord[2], 1])
        second_arg = np.reshape(second_arg,[-1,1])
        mni_coord = np.dot(T,second_arg)

        return np.reshape(mni_coord[0:3],[1,-1])

# centroid of M1 
from scipy import ndimage

m1_centre_of_mass = ndimage.measurements.center_of_mass(m1_narray)
m1_centre_of_mass = matrix_to_mni(m1_centre_of_mass, AAL3_atlas.affine)[0]       
print(m1_centre_of_mass)

print('wp1a')
dist_wp1a = []
for point in wp1a_elect_anod:
    dist = np.linalg.norm(m1_centre_of_mass-point)
    dist_wp1a.append(dist)

print(np.mean(dist_wp1a))
print(np.std(dist_wp1a))

print('wp2a')
dist_wp2a = []
for point in wp2a_elect_anod:
    dist = np.linalg.norm(m1_centre_of_mass-point)
    dist_wp2a.append(dist)

print(np.mean(dist_wp2a))
print(np.std(dist_wp2a))

[-38.43023256  -7.46142938  49.14038571]
wp1a
32.479054845704404
13.238496282116746
wp2a
29.179912145252146
6.485355563969397


In [212]:
# difference between wp1a average elct pos and wp2a average elect pos
dist = np.linalg.norm(np.asarray(wp1a_mean_point)-np.asarray(wp2a_mean_point))
dist

24.21790514044155